name: NodeJS Build Process

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - id: version
      uses: yadickson/actions/version@v1
    - run: echo "project version ${PROJECT_VERSION}"
      shell: bash
      env:
        PROJECT_VERSION: ${{ steps.version.outputs.version }}

  build:
    needs: version
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm t

    - name: Coverage
      run: npm run test:coverage

    - name: Mutation Test
      run: npm run test:mutation

  badge:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: 20

    - name: Coverage
      run: |
        npm i
        npm t
        npm run test:coverage

    - name: Badge
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: 2edc636fc2ff6aff4b056d455f3290be
        token: ${{ secrets.GIST_TOKEN }}
